### ISSUE TITLE
#movingtogitlab

### ISSUE THREAD

**Issue by mjenczmyk** [packt-cli/Packt-Publishing-Free-Learning#200]
Hi,

I'm not the owner of this repository, but for some time now I've been actively maintaining this repository. I'm also the maintainer of the PyPi package allowing for easy installation of the script.

I didn't like the fact that the GitHub has been acquired by Microsoft, but I continued to use GitHub to maintain this package - for the sake of the community. Also the communication with this repository's owner for some time was becoming much harder - but I don't blame @luk6xff for that, he did a great job writing this script from the scratch and maintaining it without any payment, we owe him a big thanks for his work.

Recently I was a bit blocked with [some](#187) [issues](#186), moreover I'll soon lose the access to the e-mail address I use when contributing on GitHub. That is a breaking point which helped me to make a decision to resign from using GitHub.

That doesn't mean I decided to stop maintaining this script - the updates will still appear on PyPi (so `pip install -U packt` will still install current version of the script, actually there is already a new release there although it's a technical release) and I'll try to resolve the upcoming and existing issues as much as the time will allow. You can find the repository with current code of the script on [GitLab](https://gitlab.com/packt-cli/packt-cli), I'll be acceptiong new contributions there.

Of course I'm not going to pretend that I'm the only one that may decide about the future of the script - so you may decide to create a new package on the PyPI (or we can talk about transferring packt package to some active maintainer of this repository). What I can do is to invite you to contribute to repository on GitLab and promise I'll try to maintain that repository as long as the time will allow.

**Comment by mjenczmyk** [comment]
Of course I'm not going to pretend that I'm the only one that may decide about the future of the script - so you may decide to create a new package on the PyPI (or we can talk about transferring `packt` package to some active maintainer of this repository). What I can do is to invite you to contribute to repository on GitLab and promise I'll try to maintain that repository as long as the time will allow.

**Comment by laurentlemercier** [comment]
Hi,
I will help you if I can.
Maybe we could change the README on github to say this is a deprecated version ?
Regards
Laurent

**Comment by mjenczmyk** [comment]
I think it's a matter of whether there is anybody who will want to maintain development here and is not willing to do that on GitLab - it's not up to me to decide if declaring that it's a abandoned fork with a depreciated version is a good idea.

**Comment by mjenczmyk** [comment]
Let's give it a try here for a bit longer ;)
